// Login Layout
import AuthLayout from "@/components/layout/auth/AuthLayout";
import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

// Load fonts
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable for Geist Sans font
  subsets: ["latin"], // Limit to Latin subset for faster load times
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable for Geist Mono font
  subsets: ["latin"], // Limit to Latin subset for faster load times
});

// Page metadata
export const metadata: Metadata = {
  title: "Login Nk-Ecommerce", // Title of the application
  description: "Generated by create next app", // Description of the application
};

export default function LoginLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthLayout>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        {children} {/* Render nested components specific to login layout */}
      </div>
    </AuthLayout>
  );
}
