// Parent Layout (Global Layout)
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Geist, Geist_Mono } from "next/font/google";
import { Metadata } from 'next';
import "./globals.css";

// Load fonts
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable for Geist Sans font
  subsets: ["latin"], // Limit to Latin subset for faster load times
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable for Geist Mono font
  subsets: ["latin"], // Limit to Latin subset for faster load times
});

// Page metadata
export const metadata: Metadata = {
  title: "Create Next App", // Title of the application
  description: "Generated by create next app", // Description of the application
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode; // Define the type for children prop
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          {children} {/* Render nested components */}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
